/**
 Copyright 2018 Google Inc. All rights reserved.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at:

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */

#import <UIKit/UIImage.h>

NS_ASSUME_NONNULL_BEGIN

typedef struct {
  uint8_t red;
  uint8_t green;
  uint8_t blue;
  uint8_t alpha;
} FBLTestRGBAColor;

/**
 Returns YES if imageA is identical to imageB in the sense that drawing the images with drawInRect
 produces identical results. Returns NO otherwise.
 */
FOUNDATION_EXPORT BOOL FBLTestImagesAreIdentical(UIImage *imageA, UIImage *imageB);

/**
 Prints the "image" represented by pixelBuffer (assumed to be of the kind generated by
 FBLTestCreateASCIISequencePixelBuffer) to the console.
 */
FOUNDATION_EXPORT void FBLTestASCIIArtPrint(FBLTestRGBAColor const *pixelBuffer, size_t width,
                                            size_t height);

/**
 Generate an "image" with pixels RGBA = [A-Z][A-Z][A-Z]255. These can be visualized in the console
 (see FBLTestASCIIArtPrint) and so are much easier to debug than real images.
 */
FOUNDATION_EXPORT FBLTestRGBAColor *FBLTestCreateASCIISequencePixelBuffer(size_t width,
                                                                          size_t height);

NS_ASSUME_NONNULL_END
